Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/jammy64"
  
  config.vm.network "private_network", ip: "192.168.56.30"
  config.vm.network "public_network"
  
  config.vm.provision "shell", path: "provision.sh"
end